import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import {
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  MaximizeIcon,
  MinimizeIcon,
  SearchIcon,
  FilterIcon,
  SortIcon,
  EditIcon,
  TrashIcon,
  CopyIcon,
  DownloadIcon,
  UploadIcon,
  ShareIcon,
  PlusIcon,
  MinusIcon,
  RefreshIcon,
  SaveIcon,
  UndoIcon,
  RedoIcon,
  ZoomInIcon,
  ZoomOutIcon,
  PrintIcon,
  ClipboardIcon,
  CheckIcon,
  XIcon,
  InfoIcon,
  WarningIcon,
  AlertCircleIcon,
  CheckCircleIcon,
  XCircleIcon,
  HelpCircleIcon,
  ShieldCheckIcon,
  BanIcon,
  LoaderIcon,
  PlayIcon,
  PauseIcon,
  ImageIcon,
  CameraIcon,
  MicrophoneIcon,
  VideoIcon,
  VolumeUpIcon,
  VolumeMuteIcon,
  SkipForwardIcon,
  SkipBackIcon,
  MusicIcon,
  HeartIcon,
  StarIcon,
  BookmarkIcon,
  BellIcon,
  ThumbsUpIcon,
  ThumbsDownIcon,
  ShareAltIcon,
  HomeIcon,
  UserIcon,
  UsersIcon,
  SettingsIcon,
  MenuIcon,
  CloseIcon,
  EyeIcon,
  EyeOffIcon,
  LockIcon,
  UnlockIcon,
  CalendarIcon,
  MailIcon,
  ClockIcon,
  GlobeIcon,
  LinkIcon,
  ExternalLinkIcon,
  CodeIcon,
  TerminalIcon,
  DatabaseIcon,
  WifiIcon,
  WifiOffIcon,
  MapPinIcon,
  LayersIcon,
  GridIcon,
  ListIcon,
  SlidersIcon,
  HashIcon,
  ZapIcon,
  AtSignIcon,
  PanelLeftIcon,
  FileIcon,
  FolderIcon,
  DocumentIcon,
  CloudIcon,
  FolderOpenIcon,
  ArchiveIcon,
  HardDriveIcon,
  CloudUploadIcon,
  CloudDownloadIcon,
  MessageIcon,
  PhoneIcon,
  InboxIcon,
  SendIcon,
  ReplyIcon,
  ForwardIcon,
  ShoppingCartIcon,
  ShoppingBagIcon,
  CreditCardIcon,
  DollarSignIcon,
  TagIcon,
  ReceiptIcon,
  StoreIcon,
  GiftIcon,
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  StrikethroughIcon,
  AlignLeftIcon,
  AlignCenterIcon,
  AlignRightIcon,
  ListOrderedIcon,
  GitHubIcon,
  XTwitterIcon,
  FacebookIcon,
  InstagramIcon,
  LinkedInIcon,
  YouTubeIcon,
  TikTokIcon,
  RedditIcon,
  DiscordIcon,
  SlackIcon,
  TwitchIcon,
  PinterestIcon,
  SpotifyIcon,
  AppleIcon,
  GoogleIcon,
  MicrosoftIcon,
  WhatsAppIcon,
  TelegramIcon,
  ThreadsIcon,
  BlueskyIcon,
  DribbbleIcon,
  FigmaIcon,
  SnapchatIcon,
} from './index';

const allIcons = [
  // Navigation
  { name: 'ArrowUpIcon', Component: ArrowUpIcon },
  { name: 'ArrowDownIcon', Component: ArrowDownIcon },
  { name: 'ArrowLeftIcon', Component: ArrowLeftIcon },
  { name: 'ArrowRightIcon', Component: ArrowRightIcon },
  { name: 'ChevronUpIcon', Component: ChevronUpIcon },
  { name: 'ChevronDownIcon', Component: ChevronDownIcon },
  { name: 'ChevronLeftIcon', Component: ChevronLeftIcon },
  { name: 'ChevronRightIcon', Component: ChevronRightIcon },
  { name: 'MoreHorizontalIcon', Component: MoreHorizontalIcon },
  { name: 'MoreVerticalIcon', Component: MoreVerticalIcon },
  { name: 'MaximizeIcon', Component: MaximizeIcon },
  { name: 'MinimizeIcon', Component: MinimizeIcon },
  // Actions
  { name: 'SearchIcon', Component: SearchIcon },
  { name: 'FilterIcon', Component: FilterIcon },
  { name: 'SortIcon', Component: SortIcon },
  { name: 'EditIcon', Component: EditIcon },
  { name: 'TrashIcon', Component: TrashIcon },
  { name: 'CopyIcon', Component: CopyIcon },
  { name: 'DownloadIcon', Component: DownloadIcon },
  { name: 'UploadIcon', Component: UploadIcon },
  { name: 'ShareIcon', Component: ShareIcon },
  { name: 'PlusIcon', Component: PlusIcon },
  { name: 'MinusIcon', Component: MinusIcon },
  { name: 'RefreshIcon', Component: RefreshIcon },
  { name: 'SaveIcon', Component: SaveIcon },
  { name: 'UndoIcon', Component: UndoIcon },
  { name: 'RedoIcon', Component: RedoIcon },
  { name: 'ZoomInIcon', Component: ZoomInIcon },
  { name: 'ZoomOutIcon', Component: ZoomOutIcon },
  { name: 'PrintIcon', Component: PrintIcon },
  { name: 'ClipboardIcon', Component: ClipboardIcon },
  // Status
  { name: 'CheckIcon', Component: CheckIcon },
  { name: 'XIcon', Component: XIcon },
  { name: 'InfoIcon', Component: InfoIcon },
  { name: 'WarningIcon', Component: WarningIcon },
  { name: 'AlertCircleIcon', Component: AlertCircleIcon },
  { name: 'CheckCircleIcon', Component: CheckCircleIcon },
  { name: 'XCircleIcon', Component: XCircleIcon },
  { name: 'HelpCircleIcon', Component: HelpCircleIcon },
  { name: 'ShieldCheckIcon', Component: ShieldCheckIcon },
  { name: 'BanIcon', Component: BanIcon },
  { name: 'LoaderIcon', Component: LoaderIcon },
  // Media
  { name: 'PlayIcon', Component: PlayIcon },
  { name: 'PauseIcon', Component: PauseIcon },
  { name: 'ImageIcon', Component: ImageIcon },
  { name: 'CameraIcon', Component: CameraIcon },
  { name: 'MicrophoneIcon', Component: MicrophoneIcon },
  { name: 'VideoIcon', Component: VideoIcon },
  { name: 'VolumeUpIcon', Component: VolumeUpIcon },
  { name: 'VolumeMuteIcon', Component: VolumeMuteIcon },
  { name: 'SkipForwardIcon', Component: SkipForwardIcon },
  { name: 'SkipBackIcon', Component: SkipBackIcon },
  { name: 'MusicIcon', Component: MusicIcon },
  // Social
  { name: 'HeartIcon', Component: HeartIcon },
  { name: 'StarIcon', Component: StarIcon },
  { name: 'BookmarkIcon', Component: BookmarkIcon },
  { name: 'BellIcon', Component: BellIcon },
  { name: 'ThumbsUpIcon', Component: ThumbsUpIcon },
  { name: 'ThumbsDownIcon', Component: ThumbsDownIcon },
  { name: 'ShareAltIcon', Component: ShareAltIcon },
  // UI
  { name: 'HomeIcon', Component: HomeIcon },
  { name: 'UserIcon', Component: UserIcon },
  { name: 'UsersIcon', Component: UsersIcon },
  { name: 'SettingsIcon', Component: SettingsIcon },
  { name: 'MenuIcon', Component: MenuIcon },
  { name: 'CloseIcon', Component: CloseIcon },
  { name: 'EyeIcon', Component: EyeIcon },
  { name: 'EyeOffIcon', Component: EyeOffIcon },
  { name: 'LockIcon', Component: LockIcon },
  { name: 'UnlockIcon', Component: UnlockIcon },
  { name: 'CalendarIcon', Component: CalendarIcon },
  { name: 'MailIcon', Component: MailIcon },
  { name: 'ClockIcon', Component: ClockIcon },
  { name: 'GlobeIcon', Component: GlobeIcon },
  { name: 'LinkIcon', Component: LinkIcon },
  { name: 'ExternalLinkIcon', Component: ExternalLinkIcon },
  { name: 'CodeIcon', Component: CodeIcon },
  { name: 'TerminalIcon', Component: TerminalIcon },
  { name: 'DatabaseIcon', Component: DatabaseIcon },
  { name: 'WifiIcon', Component: WifiIcon },
  { name: 'WifiOffIcon', Component: WifiOffIcon },
  { name: 'MapPinIcon', Component: MapPinIcon },
  { name: 'LayersIcon', Component: LayersIcon },
  { name: 'GridIcon', Component: GridIcon },
  { name: 'ListIcon', Component: ListIcon },
  { name: 'SlidersIcon', Component: SlidersIcon },
  { name: 'HashIcon', Component: HashIcon },
  { name: 'ZapIcon', Component: ZapIcon },
  { name: 'AtSignIcon', Component: AtSignIcon },
  { name: 'PanelLeftIcon', Component: PanelLeftIcon },
  // File
  { name: 'FileIcon', Component: FileIcon },
  { name: 'FolderIcon', Component: FolderIcon },
  { name: 'DocumentIcon', Component: DocumentIcon },
  { name: 'CloudIcon', Component: CloudIcon },
  { name: 'FolderOpenIcon', Component: FolderOpenIcon },
  { name: 'ArchiveIcon', Component: ArchiveIcon },
  { name: 'HardDriveIcon', Component: HardDriveIcon },
  { name: 'CloudUploadIcon', Component: CloudUploadIcon },
  { name: 'CloudDownloadIcon', Component: CloudDownloadIcon },
  // Communication
  { name: 'MessageIcon', Component: MessageIcon },
  { name: 'PhoneIcon', Component: PhoneIcon },
  { name: 'InboxIcon', Component: InboxIcon },
  { name: 'SendIcon', Component: SendIcon },
  { name: 'ReplyIcon', Component: ReplyIcon },
  { name: 'ForwardIcon', Component: ForwardIcon },
  // Commerce
  { name: 'ShoppingCartIcon', Component: ShoppingCartIcon },
  { name: 'ShoppingBagIcon', Component: ShoppingBagIcon },
  { name: 'CreditCardIcon', Component: CreditCardIcon },
  { name: 'DollarSignIcon', Component: DollarSignIcon },
  { name: 'TagIcon', Component: TagIcon },
  { name: 'ReceiptIcon', Component: ReceiptIcon },
  { name: 'StoreIcon', Component: StoreIcon },
  { name: 'GiftIcon', Component: GiftIcon },
  // Editing
  { name: 'BoldIcon', Component: BoldIcon },
  { name: 'ItalicIcon', Component: ItalicIcon },
  { name: 'UnderlineIcon', Component: UnderlineIcon },
  { name: 'StrikethroughIcon', Component: StrikethroughIcon },
  { name: 'AlignLeftIcon', Component: AlignLeftIcon },
  { name: 'AlignCenterIcon', Component: AlignCenterIcon },
  { name: 'AlignRightIcon', Component: AlignRightIcon },
  { name: 'ListOrderedIcon', Component: ListOrderedIcon },
  // Brands
  { name: 'GitHubIcon', Component: GitHubIcon },
  { name: 'XTwitterIcon', Component: XTwitterIcon },
  { name: 'FacebookIcon', Component: FacebookIcon },
  { name: 'InstagramIcon', Component: InstagramIcon },
  { name: 'LinkedInIcon', Component: LinkedInIcon },
  { name: 'YouTubeIcon', Component: YouTubeIcon },
  { name: 'TikTokIcon', Component: TikTokIcon },
  { name: 'RedditIcon', Component: RedditIcon },
  { name: 'DiscordIcon', Component: DiscordIcon },
  { name: 'SlackIcon', Component: SlackIcon },
  { name: 'TwitchIcon', Component: TwitchIcon },
  { name: 'PinterestIcon', Component: PinterestIcon },
  { name: 'SpotifyIcon', Component: SpotifyIcon },
  { name: 'AppleIcon', Component: AppleIcon },
  { name: 'GoogleIcon', Component: GoogleIcon },
  { name: 'MicrosoftIcon', Component: MicrosoftIcon },
  { name: 'WhatsAppIcon', Component: WhatsAppIcon },
  { name: 'TelegramIcon', Component: TelegramIcon },
  { name: 'ThreadsIcon', Component: ThreadsIcon },
  { name: 'BlueskyIcon', Component: BlueskyIcon },
  { name: 'DribbbleIcon', Component: DribbbleIcon },
  { name: 'FigmaIcon', Component: FigmaIcon },
  { name: 'SnapchatIcon', Component: SnapchatIcon },
];

describe('Built-in Icons', () => {
  it.each(allIcons)('$name renders an SVG', ({ Component }) => {
    const { container } = render(<Component />);
    expect(container.querySelector('svg')).toBeInTheDocument();
  });

  it.each(allIcons)('$name is decorative by default (aria-hidden)', ({ Component }) => {
    const { container } = render(<Component />);
    expect(container.querySelector('svg')).toHaveAttribute('aria-hidden', 'true');
  });

  it.each(allIcons)('$name renders with accessible label', ({ Component, name }) => {
    render(<Component label={name} />);
    expect(screen.getByRole('img', { name })).toBeInTheDocument();
  });

  it.each(allIcons)('$name supports size prop', ({ Component }) => {
    const { container } = render(<Component size="lg" />);
    const svg = container.querySelector('svg');
    const cls = svg?.getAttribute('class') ?? '';
    expect(cls).toContain('h-6');
    expect(cls).toContain('w-6');
  });

  it.each(allIcons)('$name forwards ref', ({ Component }) => {
    const ref = { current: null as SVGSVGElement | null };
    render(<Component ref={ref} />);
    expect(ref.current).toBeInstanceOf(SVGSVGElement);
  });

  it.each(allIcons)('$name renders SVG content', ({ Component }) => {
    const { container } = render(<Component />);
    const svg = container.querySelector('svg');
    expect(svg).toBeInTheDocument();
    expect(svg!.childElementCount).toBeGreaterThan(0);
  });
});
