export { Icon } from './Icon';
export type { IconProps, IconSize } from './Icon.types';

export { IconAdapter } from './IconAdapter';
export type { IconAdapterProps } from './IconAdapter.types';

// Built-in icons
export type { NamedIconProps } from './icons';
export { createLucideIcon } from './icons';
export {
  // Navigation
  ArrowUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ChevronUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  MoreHorizontalIcon,
  MoreVerticalIcon,
  MaximizeIcon,
  MinimizeIcon,
  // Actions
  SearchIcon,
  FilterIcon,
  SortIcon,
  EditIcon,
  TrashIcon,
  CopyIcon,
  DownloadIcon,
  UploadIcon,
  ShareIcon,
  PlusIcon,
  MinusIcon,
  RefreshIcon,
  SaveIcon,
  UndoIcon,
  RedoIcon,
  ZoomInIcon,
  ZoomOutIcon,
  PrintIcon,
  ClipboardIcon,
  // Status
  CheckIcon,
  XIcon,
  InfoIcon,
  WarningIcon,
  AlertCircleIcon,
  CheckCircleIcon,
  XCircleIcon,
  HelpCircleIcon,
  ShieldCheckIcon,
  BanIcon,
  LoaderIcon,
  // Media
  PlayIcon,
  PauseIcon,
  ImageIcon,
  CameraIcon,
  MicrophoneIcon,
  VideoIcon,
  VolumeUpIcon,
  VolumeMuteIcon,
  SkipForwardIcon,
  SkipBackIcon,
  MusicIcon,
  // Social
  HeartIcon,
  StarIcon,
  BookmarkIcon,
  BellIcon,
  ThumbsUpIcon,
  ThumbsDownIcon,
  ShareAltIcon,
  // UI
  HomeIcon,
  UserIcon,
  UsersIcon,
  SettingsIcon,
  MenuIcon,
  CloseIcon,
  EyeIcon,
  EyeOffIcon,
  LockIcon,
  UnlockIcon,
  CalendarIcon,
  MailIcon,
  ClockIcon,
  GlobeIcon,
  LinkIcon,
  ExternalLinkIcon,
  CodeIcon,
  TerminalIcon,
  DatabaseIcon,
  WifiIcon,
  WifiOffIcon,
  MapPinIcon,
  LayersIcon,
  GridIcon,
  ListIcon,
  SlidersIcon,
  HashIcon,
  ZapIcon,
  AtSignIcon,
  PanelLeftIcon,
  // File
  FileIcon,
  FolderIcon,
  DocumentIcon,
  CloudIcon,
  FolderOpenIcon,
  ArchiveIcon,
  HardDriveIcon,
  CloudUploadIcon,
  CloudDownloadIcon,
  // Communication
  MessageIcon,
  PhoneIcon,
  InboxIcon,
  SendIcon,
  ReplyIcon,
  ForwardIcon,
  // Commerce
  ShoppingCartIcon,
  ShoppingBagIcon,
  CreditCardIcon,
  DollarSignIcon,
  TagIcon,
  ReceiptIcon,
  StoreIcon,
  GiftIcon,
  // Editing
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  StrikethroughIcon,
  AlignLeftIcon,
  AlignCenterIcon,
  AlignRightIcon,
  ListOrderedIcon,
  // Brands
  createBrandIcon,
  GitHubIcon,
  XTwitterIcon,
  FacebookIcon,
  InstagramIcon,
  LinkedInIcon,
  YouTubeIcon,
  TikTokIcon,
  RedditIcon,
  DiscordIcon,
  SlackIcon,
  TwitchIcon,
  PinterestIcon,
  SpotifyIcon,
  AppleIcon,
  GoogleIcon,
  MicrosoftIcon,
  WhatsAppIcon,
  TelegramIcon,
  ThreadsIcon,
  BlueskyIcon,
  DribbbleIcon,
  FigmaIcon,
  SnapchatIcon,
} from './icons';
